vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
       #dish_images:
           #uri_prefix: /images/plat
           #upload_destination: '%kernel.project_dir%/public/images/plats'
           #namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
